# Generated by Django 3.2.12 on 2022-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudId', models.CharField(max_length=5)),
                ('Mark01', models.CharField(max_length=20)),
                ('Mark02', models.CharField(max_length=10)),
            ],
        ),
    ]
